[tool.poetry]
name = "mizu"
version = "0.1.0"
description = ""
authors = ["Viet Dinh <vhd8@case.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
taichi = "^1.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
